using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace UAEZPSynthesisPatcher;

public static class Program
{
    private static Lazy<Settings> _settings = null!;

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings(
                "Settings",
                "settings.json",
                out _settings)
            .SetTypicalOpen(
                GameRelease.SkyrimSE,
                "UAEZPSynthesisPatcher.esp")
            .Run(args);
    }

    public static void RunPatch(
        IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        Settings settings = _settings.Value;
        MilestoneGuard.EnsureReadOnly(settings);

        PlanningRun run = StatePlanner.Build(state, settings);
        Console.WriteLine(DryRunReport.Render(run, settings));
    }
}
